# Variables

In [1]:
import tensorflow as tf

In [2]:
v1 = tf.Variable(5)
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>

In [5]:
v2 = tf.Variable([5,2,8], dtype= tf.float32)
v2

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([5., 2., 8.], dtype=float32)>

In [6]:
v3 = tf.Variable([1,2,3])
v4 = tf.Variable([5,6,7])

In [7]:
add_v = tf.add(v3, v4)
add_v

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6,  8, 10])>

In [9]:
mult_v = tf.multiply(v3, v4)
mult_v

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 12, 21])>

In [10]:
import numpy as np

In [11]:
v3

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

In [12]:
v3.numpy()

array([1, 2, 3])

In [13]:
v3

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

In [15]:
v3.assign([5,10,15])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([ 5, 10, 15])>

In [16]:
v3

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 5, 10, 15])>

In [17]:
x1 = tf.constant([1,2,3])
x1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [18]:
x1.assign([5,10,15])

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [19]:
v3

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 5, 10, 15])>

In [20]:
v10 = tf.Variable(v3)
v10

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 5, 10, 15])>

In [21]:
v3

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 5, 10, 15])>